# Generated by Django 2.2 on 2020-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('tellphone', models.IntegerField(unique=True, verbose_name='手机号码')),
                ('messange', models.CharField(max_length=1024, verbose_name='留言信息')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyFlow',
        ),
    ]
