# Generated by Django 2.2 on 2020-08-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managent', '0003_auto_20200817_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messange',
            new_name='message',
        ),
    ]
