# Generated by Django 2.2 on 2020-08-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managent', '0004_auto_20200817_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=128, verbose_name='姓名'),
        ),
    ]
