# Generated by Django 2.2 on 2020-08-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managent', '0005_auto_20200817_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tellphone',
            field=models.CharField(max_length=128, unique=True, verbose_name='手机号码'),
        ),
    ]
