# Generated by Django 2.2 on 2020-08-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managent', '0007_auto_20200817_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='mess',
        ),
    ]
