# Generated by Django 2.2 on 2020-08-17 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managent', '0008_auto_20200817_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='c_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
