# Generated by Django 2.2 on 2020-08-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managent', '0009_message_c_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
